### ISSUE TITLE
Repo init error

### ISSUE THREAD

**Issue by PrasadParulkar** [maruos/manifest#24]
MaruOS 0.7 is not able to get initialized properly and syncing is not possible.
Workaround: init repo with maru-0.6, then shift branch to maru-0.7

**Comment by pdsouza** [comment]
Thanks for the workaround @PrasadParulkar ! Let's take a look when we get a chance @utzcoz

**Comment by utzcoz** [comment]
I can check it this weekend.

**Comment by utzcoz** [comment]
@PrasadParulkar Please try maru-0.7 branch again, and let me know if it still have issues.

**Comment by PrasadParulkar** [comment]
@utzcoz Tried syncing repo again, issue was fixed.
